/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.receiptui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

import ui.util.MyFrame;
import util.CurrentTime;
import util.enumData.ResultMessage;
import Exception.NotFoundMoneyInAndOutException;
import VO.BusinessFormVO;
import VO.Receipt.CashRepVO;
import VO.Receipt.CashVO;
import VO.Receipt.PayRepVO;
import VO.Receipt.PayVO;
import bl.controllerfactorybl.ControllerFactoryImpl;
import blservice.formblservice.BusinessFormBLService;

/**
 *
 * @author apple
 */
public class BusinessForm extends javax.swing.JPanel {
public static void main(String[] args) {
	new BusinessForm();
}
    /**
     * Creates new form 经营情况表
     */
    public BusinessForm() {    	
    	ctr=ControllerFactoryImpl.getInstance().getBusinessFromController();
    	initComponents();
        frame=new MyFrame(900, 600, this);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startTimeLabel = new javax.swing.JLabel();
        startTimeText = new javax.swing.JTextField();
        endTimeLabel = new javax.swing.JLabel();
        endTimeText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cashRepTable = new javax.swing.JTable();
        cashLabel = new javax.swing.JLabel();
        payLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        payRepTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        resultMsgText = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        startTimeLabel.setText("开始日期:");

        endTimeLabel.setText("结束日期:");

        cashRepTable.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "日期", "编号", "收款金额"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        cashRepTable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(cashRepTable);

        cashLabel.setText("收款项");

        payLabel.setText("付款项");

        payRepTable.setModel(new javax.swing.table.DefaultTableModel(
           null,
            new String [] {
                "日期", "编号", "支付金额","备注"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        payRepTable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(payRepTable);


        backButton.setText("返回");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        resultMsgText.setEditable(false);

        findButton.setText("查看");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });
        
        startTimeText.setText("例如:2015-11-02");
        startTimeText.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
            	// TODO Auto-generated method stub
            	startTimeText.setText("");
            }
        });
        
       initLayout();
    }

    private void initLayout() {
    	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultMsgText)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(backButton)
                        .addGap(198, 198, 198))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(cashLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(payLabel)))
                .addGap(196, 196, 196))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(endTimeLabel)
                    .addComponent(startTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startTimeText, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(endTimeText))
                .addGap(18, 18, 18)
                .addComponent(findButton)
                .addGap(280, 280, 280))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTimeLabel)
                    .addComponent(startTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endTimeLabel)
                    .addComponent(endTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashLabel)
                    .addComponent(payLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(resultMsgText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
	}
	
    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
         resultMsgText.setText("");
         //TODO 
    	String startT=startTimeText.getText();
    	String endT=endTimeText.getText();
    	ResultMessage msgt=datesIfValid(startT,endT);
    	
    	if(msgt==ResultMessage.VALID){
    		try {
				formVO=ctr.show(startT, endT);
			
				ArrayList<ArrayList<CashRepVO>>cashvos=formVO.moneyInRecord;
				ArrayList<PayRepVO> payvos=formVO.moneyOutRecord;
				int count=0;
				for(PayRepVO vo:payvos){
					count+=vo.payVOs.size();
				}
				payObjects=new Object[count][4];
				count=0;
				for(PayRepVO repvo:payvos){
					for (PayVO vo : repvo.payVOs) {
						payObjects[count][0] = repvo.date;
						payObjects[count][1] = repvo.num;
						payObjects[count][2] = vo.money;
						payObjects[count][3]= vo.payThing;
						count++;
					}
				}
				payRepTable.setModel(new javax.swing.table.DefaultTableModel(
			            payObjects,
			            new String [] {
			                "日期", "编号", "支付金额","备注"
			            }
			        ) );
				count=0;
				for(ArrayList<CashRepVO> repvos:cashvos){
					for(CashRepVO repvo:repvos){
						count+=repvo.cashVOs.size();
					}
				}
				cashObjects=new Object[count][3];
				count=0;
				for(ArrayList<CashRepVO> repvos:cashvos){
					for(CashRepVO repvo:repvos){
						for(CashVO vo:repvo.cashVOs){
							cashObjects[count][0]=repvo.date;
							cashObjects[count][1]=repvo.num;
							cashObjects[count][2]=vo.money;
							count++;
						}
					}
				}
		    	 cashRepTable.setModel(new javax.swing.table.DefaultTableModel(
		            cashObjects,
		            new String [] {
		                "日期", "编号", "收款金额"
		            }
		        ));
		    	 System.out.println("收款单行数"+count);
    		} catch (NotFoundMoneyInAndOutException e) {
	     	    showFeedback(ResultMessage.NOT_FOUND_FINACIAL);
			}
		}else{
			showFeedback(msgt);
		}
    	
    }
    private void showFeedback(ResultMessage msg) {
		resultMsgText.setText(ResultMessage.toFriendlyString(msg));
	}
/**
 * 合法返回VALID
 * @param startT
 * @param endT
 * @return
 */
    public static ResultMessage datesIfValid(String startT,String endT){
    	if(startT.length()==0||endT.length()==0){
    		return ResultMessage.NOT_COMPLETED;
    	}
    	if(!(dtIfValid(startT)&&dtIfValid(endT))){
    		return ResultMessage.WRONG_FORMAT;
    	}else{
    		if(CurrentTime.ifearlier(startT, endT)){
    			return ResultMessage.VALID;
    		}else if((!CurrentTime.ifearlier(startT, endT))&&(!CurrentTime.ifearlier(endT, startT))){
    			return ResultMessage.VALID;
    		}else{
    			return ResultMessage.WRONG_ORDER_OF_DATE;
    		}
    	}
    }
	private static Boolean dtIfValid(String date) {
		ArrayList<Integer> loc=new ArrayList<Integer>(2);
		for(int i=0;i<date.length();i++){
			char c=date.charAt(i);
			if(c=='-'){
				loc.add(i);
			}else if(!(c>='0'&&c<='9')){
				return false;
			}
		}
		if(loc.size()!=2) {
			return false;
		}else{//有两个短线~
			//第一个短线前没数字   后一个短线后没数字  两短线间没数字
			if(loc.get(0)==0||
					loc.get(1)==date.length()-1||
					(loc.get(1)-loc.get(0))==1){
				return false;
			}
		}
		return true;
	}
	
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
         frame.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel cashLabel,startTimeLabel,endTimeLabel;
    private javax.swing.JTable cashRepTable,payRepTable;
    private javax.swing.JButton findButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel payLabel;
    private javax.swing.JTextField resultMsgText;
    private javax.swing.JTextField startTimeText,endTimeText;
    private MyFrame frame;
    private BusinessFormBLService ctr;
    private BusinessFormVO formVO;
    private Object[][] cashObjects,payObjects;
    // End of variables declaration//GEN-END:variables

}
