/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.receiptui;

/**
 *
 * @author apple
 */
public class IOTable extends .JPanel {

    /**
     * Creates new form 成本收益表
     */
    public IOTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startDateLabel = new .JLabel();
        startDateText = new .JTextField();
        endDateLabel = new .JLabel();
        endDateText = new .JTextField();
        costLabel = new .JLabel();
        costText = new .JTextField();
        incomeLabel = new .JLabel();
        incomeText = new .JTextField();
        realIncomeLabel = new .JLabel();
        realIncomeText = new .JTextField();
        okButton = new .JButton();
        resetButton = new .JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        startDateLabel.setText("开始日期:");

        endDateLabel.setText("结束时间:");

        costLabel.setText("成本:");

        costText.setText("0");

        incomeLabel.setText("总收入:");

        incomeText.setText("0");

        realIncomeLabel.setText("净收入:");

        realIncomeText.setText("0");

        okButton.setText("确定");

        resetButton.setText("重置");

        .GroupLayout layout = new .GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                    .addComponent(realIncomeLabel)
                    .addComponent(costLabel)
                    .addComponent(startDateLabel)
                    .addComponent(incomeLabel))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resetButton)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                                .addComponent(startDateText, .GroupLayout.PREFERRED_SIZE, 112, .GroupLayout.PREFERRED_SIZE)
                                .addComponent(costText, .GroupLayout.PREFERRED_SIZE, 59, .GroupLayout.PREFERRED_SIZE)
                                .addComponent(incomeText, .GroupLayout.PREFERRED_SIZE, 59, .GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addComponent(okButton))
                    .addComponent(realIncomeText, .GroupLayout.PREFERRED_SIZE, 59, .GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(endDateLabel)
                        .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endDateText, .GroupLayout.PREFERRED_SIZE, 108, .GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDateLabel)
                    .addComponent(startDateText, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateLabel)
                    .addComponent(endDateText, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(costLabel)
                    .addComponent(costText, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(incomeText, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                    .addComponent(incomeLabel))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(realIncomeLabel)
                    .addComponent(realIncomeText, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(resetButton))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private .JLabel costLabel;
    private .JTextField costText;
    private .JLabel endDateLabel;
    private .JTextField endDateText;
    private .JLabel incomeLabel;
    private .JTextField incomeText;
    private .JButton okButton;
    private .JLabel realIncomeLabel;
    private .JTextField realIncomeText;
    private .JButton resetButton;
    private .JLabel startDateLabel;
    private .JTextField startDateText;
    // End of variables declaration//GEN-END:variables
}
