/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.receiptui;

/**
 *
 * @author apple
 */
public class PayRepRent extends .JPanel {

    /**
     * Creates new form PayRep租金
     */
    public PayRepRent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new .JTextField();
        jLabel1 = new .JLabel();
        jLabel2 = new .JLabel();
        jTextField2 = new .JTextField();
        jLabel3 = new .JLabel();
        jTextField3 = new .JTextField();
        jLabel4 = new .JLabel();
        jTextField4 = new .JTextField();
        jScrollPane1 = new .JScrollPane();
        jTable1 = new .JTable();
        jTextField5 = new .JTextField();
        jLabel6 = new .JLabel();
        jTextField6 = new .JTextField();
        jLabel7 = new .JLabel();
        jComboBox1 = new .JComboBox();
        jButton1 = new .JButton();
        jButton2 = new .JButton();
        jLabel8 = new .JLabel();
        jButton3 = new .JButton();
        resultMsgText = new .JTextField();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("收租人名字:");

        jLabel3.setText("收租人手机:");

        jLabel4.setText("租金:");

        jTextField4.setText("0");

        jTable1.setModel(new .table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "收租人名字", "手机", "金额", "备注"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        jTextField5.setEditable(false);
        jTextField5.setText("0");

        jLabel6.setText("账户余额:");

        jTextField6.setEditable(false);
        jTextField6.setText("0");

        jLabel7.setText("付款账户:");

        jComboBox1.setModel(new .DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("取消");

        jButton2.setText("确认");

        jLabel8.setText("总计:");

        jButton3.setText("添加");

        .GroupLayout layout = new .GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, .GroupLayout.PREFERRED_SIZE, 113, .GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4, .GroupLayout.PREFERRED_SIZE, 65, .GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jButton3))
                            .addComponent(jTextField2, .GroupLayout.PREFERRED_SIZE, 77, .GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, .GroupLayout.PREFERRED_SIZE, 246, .GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, .GroupLayout.PREFERRED_SIZE, 69, .GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jButton1))
                                            .addComponent(jTextField6, .GroupLayout.PREFERRED_SIZE, 68, .GroupLayout.PREFERRED_SIZE))
                                        .addGap(68, 68, 68)
                                        .addComponent(jButton2))))
                            .addComponent(jScrollPane1, .GroupLayout.PREFERRED_SIZE, 391, .GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(resultMsgText)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField2, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, .GroupLayout.PREFERRED_SIZE, 275, .GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(resultMsgText, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private .JButton jButton1;
    private .JButton jButton2;
    private .JButton jButton3;
    private .JComboBox jComboBox1;
    private .JLabel jLabel1;
    private .JLabel jLabel2;
    private .JLabel jLabel3;
    private .JLabel jLabel4;
    private .JLabel jLabel6;
    private .JLabel jLabel7;
    private .JLabel jLabel8;
    private .JScrollPane jScrollPane1;
    private .JTable jTable1;
    private .JTextField jTextField1;
    private .JTextField jTextField2;
    private .JTextField jTextField3;
    private .JTextField jTextField4;
    private .JTextField jTextField5;
    private .JTextField jTextField6;
    private .JTextField resultMsgText;
    // End of variables declaration//GEN-END:variables
}
