/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.financialstaffui;

import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingConstants;
import javax.swing.event.MouseInputListener;
import javax.swing.table.DefaultTableCellRenderer;

import org.apache.poi.hssf.record.formula.functions.If;

import main.MainFrame;
import ui.componentfactory.ComponentFactory;
import ui.receiptui.BusinessForm;
import ui.receiptui.ProfitForm;
import ui.receiptui.generalUI.PayRep;
import util.InputCheck;
import util.enumData.Authority;
import util.enumData.LogType;
import util.enumData.ModifyState;
import util.enumData.ResultMessage;
import VO.LogVO;
import VO.ManagementVO.BankAccountVO;
import VO.ManagementVO.BankAccountVOPlus;
import bl.controllerfactorybl.ControllerFactoryImpl;
import bl.loginbl.Loginbl;
import blservice.controllerfactoryblservice.ControllerFactoryblService;
import blservice.logblservice.LogBLService;
import blservice.managementblservice.bankaccountblservice.BankAccountBLService;

/**
 *
 * @author 1
 * 
 */

public class FinancialStaffJFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form FinancialStaffJFrame
	 */
	public FinancialStaffJFrame() {
		ctr_log = ControllerFactoryImpl.getInstance().getLogController();
		this.setVisible(true);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
	
		this.setResizable(false);
		this.setVisible(true);
		currentOptorId = Loginbl.getCurrentOptorId();
		String optorName = Loginbl.getCurrentOptorName();
		currentAuthority = Loginbl.getCurrentAuthority();
		setBankAccountVOs();
		initialVariables();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		financialjPanel.setPreferredSize(new java.awt.Dimension(830, 590));

		currentAccountNumjLabel.setText(currentOptorId);
		currentAccountNumjLabel.setToolTipText("当前用户账号");

		accountNamejLabel.setText(optorName);
		accountNamejLabel.setToolTipText("当前用户姓名");

		currentAuthorityjLabel.setText(Authority.getAuthority(
				Integer.parseInt(currentOptorId.substring(7, 8))).getValue());
		currentAuthorityjLabel.setToolTipText("当前用户职位");

		statejLabel.setText("空闲");

		stateTitlejLabel.setText("状态：");

		finacialjTabbedPane.setToolTipText("查看成本收益表");
		finacialjTabbedPane.setPreferredSize(new java.awt.Dimension(830, 465));

		financialManagejPanel
				.setPreferredSize(new java.awt.Dimension(830, 460));

		financilManageTitlejLabel.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
		financilManageTitlejLabel.setText("收支管理");

		paymentIconjPanel.setBackground(new java.awt.Color(240, 0, 240));
		paymentIconjPanel.setToolTipText("");
		paymentIconjPanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				paymentIconjPanelMouseReleased(evt);
			}
		});

		javax.swing.GroupLayout paymentIconjPanelLayout = new javax.swing.GroupLayout(
				paymentIconjPanel);
		paymentIconjPanel.setLayout(paymentIconjPanelLayout);
		paymentIconjPanelLayout.setHorizontalGroup(paymentIconjPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 200, Short.MAX_VALUE));
		paymentIconjPanelLayout.setVerticalGroup(paymentIconjPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 180, Short.MAX_VALUE));

		paymentjButton.setText("生成付款单");
		paymentjButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				paymentjButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout financialManagejPanelLayout = new javax.swing.GroupLayout(
				financialManagejPanel);
		financialManagejPanel.setLayout(financialManagejPanelLayout);
		financialManagejPanelLayout
				.setHorizontalGroup(financialManagejPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								financialManagejPanelLayout
										.createSequentialGroup()
										.addGroup(
												financialManagejPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																financialManagejPanelLayout
																		.createSequentialGroup()
																		.addGap(363,
																				363,
																				363)
																		.addComponent(
																				paymentjButton))
														.addGroup(
																financialManagejPanelLayout
																		.createSequentialGroup()
																		.addGap(306,
																				306,
																				306)
																		.addComponent(
																				paymentIconjPanel,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																financialManagejPanelLayout
																		.createSequentialGroup()
																		.addGap(383,
																				383,
																				383)
																		.addComponent(
																				financilManageTitlejLabel)))
										.addContainerGap(319, Short.MAX_VALUE)));
		financialManagejPanelLayout
				.setVerticalGroup(financialManagejPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								financialManagejPanelLayout
										.createSequentialGroup()
										.addGap(27, 27, 27)
										.addComponent(financilManageTitlejLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												76, Short.MAX_VALUE)
										.addComponent(
												paymentIconjPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(40, 40, 40)
										.addComponent(paymentjButton)
										.addContainerGap(132, Short.MAX_VALUE)));

		finacialjTabbedPane.addTab("收支管理", financialManagejPanel);

		inititalBankAccountJPanel();

		initialFormJpanel();
		initialLogjPanel();

		javax.swing.GroupLayout logjPanelLayout = new javax.swing.GroupLayout(
				logjPanel);
		logjPanel.setLayout(logjPanelLayout);
		logjPanelLayout
				.setHorizontalGroup(logjPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								logjPanelLayout
										.createSequentialGroup()
										.addComponent(logSDatejLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												logSYearjComboBox,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(logSYearjLabel)
										.addGap(6, 6, 6)
										.addGroup(
												logjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																583,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																logjPanelLayout
																		.createSequentialGroup()
																		.addGroup(
																				logjPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								logjPanelLayout
																										.createSequentialGroup()
																										.addComponent(
																												logSMonthjComboBox,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												logSMonthjLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												logSDatejComboBox,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												logStartDayjLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												logEDatejLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												logEYearjComboBox,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												logEYearjLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												logEMonthjComboBox,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												logEMonthjLabel))
																						.addGroup(
																								logjPanelLayout
																										.createSequentialGroup()
																										.addGap(232,
																												232,
																												232)
																										.addComponent(
																												logTitlejLabel,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												54,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGroup(
																				logjPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								logjPanelLayout
																										.createSequentialGroup()
																										.addGap(4,
																												4,
																												4)
																										.addComponent(
																												logEDatejComboBox,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												logEDayjLabel,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												12,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												logTypejLabel)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												logTypejComboBox,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												107,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								logjPanelLayout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												findLogjButton)))))
										.addGap(106, 106, 106))
						.addGroup(
								logjPanelLayout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												logjPanelLayout
														.createSequentialGroup()
														.addGap(0, 606,
																Short.MAX_VALUE)
														.addComponent(
																jSeparator5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																160,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(59, 59, 59))));
		logjPanelLayout
				.setVerticalGroup(logjPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								logjPanelLayout
										.createSequentialGroup()
										.addContainerGap(20, Short.MAX_VALUE)
										.addGroup(
												logjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																logSDatejLabel)
														.addComponent(
																logSYearjLabel)
														.addComponent(
																logSMonthjLabel)
														.addComponent(
																logSYearjComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																logSMonthjComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																logSDatejComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																logEDatejLabel)
														.addComponent(
																logEYearjLabel)
														.addComponent(
																logEMonthjLabel)
														.addComponent(
																logEDayjLabel)
														.addComponent(
																logEYearjComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																logEMonthjComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																logEDatejComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																logTypejLabel)
														.addComponent(
																logTypejComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																logStartDayjLabel))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												16, Short.MAX_VALUE)
										.addGroup(
												logjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																logTitlejLabel)
														.addComponent(
																findLogjButton))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												26, Short.MAX_VALUE)
										.addComponent(
												jScrollPane4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												360,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(27, Short.MAX_VALUE))
						.addGroup(
								logjPanelLayout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												logjPanelLayout
														.createSequentialGroup()
														.addContainerGap(286,
																Short.MAX_VALUE)
														.addComponent(
																jSeparator5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(205, 205, 205))));

		finacialjTabbedPane.addTab("日志查看", logjPanel);

		// initialNewFinanceJpanel();
		jLabel6.setFont(new Font("宋体",Font.BOLD,12));
		jLabel6.setText("财务人员");

		exitjButton.setText("退出系统");
		exitjButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitjButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout financialjPanelLayout = new javax.swing.GroupLayout(
				financialjPanel);
		financialjPanel.setLayout(financialjPanelLayout);
		financialjPanelLayout
				.setHorizontalGroup(financialjPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								financialjPanelLayout
										.createSequentialGroup()
										.addComponent(stateTitlejLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												statejLabel,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addComponent(finacialjTabbedPane,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGroup(
								financialjPanelLayout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel6)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								financialjPanelLayout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(currentAccountNumjLabel)
										.addGap(29, 29, 29)
										.addComponent(accountNamejLabel)
										.addGap(26, 26, 26)
										.addComponent(currentAuthorityjLabel)
										.addGap(18, 18, 18)
										.addComponent(exitjButton)
										.addGap(40, 40, 40)));
		financialjPanelLayout
				.setVerticalGroup(financialjPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								financialjPanelLayout
										.createSequentialGroup()
										.addComponent(
												jLabel6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												15,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												financialjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																accountNamejLabel)
														.addComponent(
																currentAuthorityjLabel)
														.addComponent(
																currentAccountNumjLabel)
														.addComponent(
																exitjButton))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												finacialjTabbedPane,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												522,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												financialjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																stateTitlejLabel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																statejLabel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																21,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(22, 22, 22)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				financialjPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				financialjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
		this.setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void initialLogjPanel() {
		// TODO Auto-generated method stub
		logjPanel.setPreferredSize(new java.awt.Dimension(830, 460));

		findLogjButton.setText("查找");
		findLogjButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				findLogjButtonMouseClicked(evt);
			}
		});
		findLogjButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				findLogjButtonActionPerformed(evt);
			}
		});

		logSDatejLabel.setText("开始日期：");

		logSYearjLabel.setText("年");

		logSMonthjLabel.setText("月");

		logTypejLabel.setText("操作类型：");
		logTypejComboBox = ComponentFactory.getLogTypeJComboBox();
		// logTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel(
		// new String[] { "所有操作", "薪水制定", "常量制定", "审批单据", "用户账户管理",
		// "银行账户管理", "人员机构管理", "司机管理", "车辆管理", "创建订单", "权限管理",
		// "查看报表", "派件", "签收订单" }));

		logTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				logTypejComboBoxActionPerformed(evt);
			}
		});

		// logSYearjComboBox.setModel(new javax.swing.DefaultComboBoxModel(
		// new String[] { "2000", "2001", "2002", "2003", "2004", "2005",
		// "2006", "2007", "2008", "2009", "2010", "2011", "2012",
		// "2013", "2014", "2015" }));
		//
		// logSDatejComboBox.setModel(new javax.swing.DefaultComboBoxModel(
		// new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9",
		// "10", "11", "12", "13", "14", "15", "16", "17", "18",
		// "9", "20", "21", "22", "23", "24", "25", "26", "27",
		// "28", "29", "30", "31" }));
		//
		// logSMonthjComboBox.setModel(new javax.swing.DefaultComboBoxModel(
		// new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9",
		// "10", "11", "12" }));
		logSYearjComboBox = ComponentFactory.getYearJComboBox(2015, 2020);
		logSMonthjComboBox = ComponentFactory.getMonthJComboBox();
		logSDatejComboBox = ComponentFactory.getDayJComboBox();

		logSMonthjComboBox
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						logSMonthjComboBoxActionPerformed(evt);
					}
				});

		logEYearjLabel.setText("年");

		logEMonthjLabel.setText("月");

		logEDayjLabel.setText("日");

		// logEYearjComboBox.setModel(new javax.swing.DefaultComboBoxModel(
		// new String[] { "2000", "2001", "2002", "2003", "2004", "2005",
		// "2006", "2007", "2008", "2009", "2010", "2011", "2012",
		// "2013", "2014", "2015" }));
		//
		// logEDatejComboBox.setModel(new javax.swing.DefaultComboBoxModel(
		// new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9",
		// "10", "11", "12", "13", "14", "15", "16", "17", "18",
		// "19", "20", "21", "22", "23", "24", "25", "26", "27",
		// "28", "29", "30", "31" }));
		//
		// logEMonthjComboBox.setModel(new javax.swing.DefaultComboBoxModel(
		// new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9",
		// "10", "11", "12" }));
		logEYearjComboBox = ComponentFactory.getYearJComboBox(2015, 2020);
		logEMonthjComboBox = ComponentFactory.getMonthJComboBox();
		logEDatejComboBox = ComponentFactory.getDayJComboBox();
		logEYearjComboBox
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						logEYearjComboBoxActionPerformed(evt);
					}
				});
		logEMonthjComboBox
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						logEMonthjComboBoxActionPerformed(evt);
					}
				});

		logEDatejLabel.setText("截止日期：");

		logTitlejLabel.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
		logTitlejLabel.setText("系统日志");

		// initialLogJTable(logVOs);
		logStartDayjLabel.setText("日");
	}

	private void initialLogJTable(ArrayList<LogVO> vos) {
		// TODO Auto-generated method stub
		assert (vos != null) : ("表格获得的日志信息为空");
		Object[][] logObjects = null;
		logObjects = new Object[vos.size()][4];
		int i = 0;
		for (java.util.Iterator<LogVO> t = vos.iterator(); t.hasNext(); i++) {
			LogVO vo = t.next();
			System.out.println("得到的log信息：" + vo.time);
			logObjects[i][0] = vo.time;
			logObjects[i][1] = vo.operationName;
			logObjects[i][2] = authorityjComboBox.getItemAt(Integer
					.parseInt(vo.operatorID.substring(7, 8)));
			logObjects[i][3] = vo.operatorID;

		}

		logjTable.setModel(new javax.swing.table.DefaultTableModel(logObjects,
				new String[] { "日期", "操做类型", "操作人员职位", "操作人员编号" }) {
			Class[] types = new Class[] { java.lang.String.class,
					JComboBox.class, JComboBox.class, java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		logjTable.getColumnModel().getColumn(1)
				.setCellEditor(new DefaultCellEditor(logTypejComboBox));
		logjTable.getColumnModel().getColumn(2)
				.setCellEditor(new DefaultCellEditor(authorityjComboBox));

		// logjTable.setRowSelectionInterval(0, 0);// 设置哪几行被选中

		logjTable.setGridColor(new java.awt.Color(0, 0, 0));
		logjTable.setName("123"); // NOI18N
		logjTable.getTableHeader().setReorderingAllowed(false);

		ComponentFactory.setJTableTextCenter(logjTable);
		jScrollPane4.setViewportView(logjTable);

	}

	private void initialNewFinanceJpanel() {
		// TODO Auto-generated method stub
		jPanel6.setPreferredSize(new java.awt.Dimension(830, 460));

		initialFinancejButton.setText("账目初始化");
		initialFinancejButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						initialFinancejButtonActionPerformed(evt);
					}
				});

		newFinancejButton.setText("新建账目");
		newFinancejButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						newFinancejButtonActionPerformed(evt);
					}
				});

		initialFinaceIconjpanel
				.setBackground(new java.awt.Color(240, 100, 240));
		initialFinaceIconjpanel.setToolTipText("");

		javax.swing.GroupLayout initialFinaceIconjpanelLayout = new javax.swing.GroupLayout(
				initialFinaceIconjpanel);
		initialFinaceIconjpanel.setLayout(initialFinaceIconjpanelLayout);
		initialFinaceIconjpanelLayout
				.setHorizontalGroup(initialFinaceIconjpanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 220, Short.MAX_VALUE));
		initialFinaceIconjpanelLayout
				.setVerticalGroup(initialFinaceIconjpanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 200, Short.MAX_VALUE));

		newFinanceIconjPanel.setBackground(new java.awt.Color(24, 240, 20));
		newFinanceIconjPanel.setToolTipText("");
		newFinanceIconjPanel
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseReleased(java.awt.event.MouseEvent evt) {
						newFinanceIconjPanelMouseReleased(evt);
					}
				});

		javax.swing.GroupLayout newFinanceIconjPanelLayout = new javax.swing.GroupLayout(
				newFinanceIconjPanel);
		newFinanceIconjPanel.setLayout(newFinanceIconjPanelLayout);
		newFinanceIconjPanelLayout
				.setHorizontalGroup(newFinanceIconjPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 200, Short.MAX_VALUE));
		newFinanceIconjPanelLayout.setVerticalGroup(newFinanceIconjPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		initialFinanceTitlejLabel.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
		initialFinanceTitlejLabel.setText("期初建账");

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGap(169, 169, 169)
										.addComponent(initialFinancejButton)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(newFinancejButton)
										.addGap(173, 173, 173))
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGap(108, 108, 108)
										.addComponent(
												initialFinaceIconjpanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												187, Short.MAX_VALUE)
										.addComponent(
												newFinanceIconjPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(110, 110, 110))
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGap(387, 387, 387)
										.addComponent(initialFinanceTitlejLabel)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGap(18, 18, 18)
										.addComponent(initialFinanceTitlejLabel)
										.addGap(75, 75, 75)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																initialFinaceIconjpanel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																newFinanceIconjPanel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																initialFinancejButton)
														.addComponent(
																newFinancejButton))
										.addGap(144, 144, 144)));

		finacialjTabbedPane.addTab("期初建账", jPanel6);

	}

	private void initialFormJpanel() {
		// TODO Auto-generated method stub
		formjPanel.setPreferredSize(new java.awt.Dimension(830, 460));
		viewProfitFormjButton.setText("查看成本收益表");
		viewProfitFormjButton.setToolTipText("");
		viewProfitFormjButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						viewProfitFormjButtonActionPerformed(evt);
					}
				});

		viewManageForm.setText("查看经营情况表");
		viewManageForm.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				viewManageFormMouseClicked(evt);
			}
		});

		formEYearjLabel.setText("年");

		formEMonthjLabel.setText("月");

		formEDatejLabel.setText("日");

		formEYearjComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "2000", "2001", "2002", "2003", "2004", "2005",
						"2006", "2007", "2008", "2009", "2010", "2011", "2012",
						"2013", "2014", "2015" }));

		formEDatejComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9",
						"10", "11", "12", "13", "14", "15", "16", "17", "18",
						"9", "20", "21", "22", "23", "24", "25", "26", "27",
						"28", "29", "30", "31" }));
		formEDatejComboBox
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						formEDatejComboBoxActionPerformed(evt);
					}
				});

		formEMonthjComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9",
						"10", "11", "12" }));
		formEMonthjComboBox
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						formEMonthjComboBoxActionPerformed(evt);
					}
				});

		formDeadLinejLabel.setText("截止日期：");
		formDeadLinejLabel.setVisible(false);
		formEDatejLabel.setVisible(false);
		formEDatejComboBox.setVisible(false);
		formEMonthjLabel.setVisible(false);
		formEMonthjComboBox.setVisible(false);
		formEYearjLabel.setVisible(false);
		formEYearjComboBox.setVisible(false);

		profitFormIcon.setBackground(new java.awt.Color(0, 240, 240));
		profitFormIcon.setToolTipText("");

		javax.swing.GroupLayout profitFormIconLayout = new javax.swing.GroupLayout(
				profitFormIcon);
		profitFormIcon.setLayout(profitFormIconLayout);
		profitFormIconLayout.setHorizontalGroup(profitFormIconLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 200, Short.MAX_VALUE));
		profitFormIconLayout.setVerticalGroup(profitFormIconLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 200, Short.MAX_VALUE));

		manageFormIcon.setBackground(new java.awt.Color(240, 240, 0));
		manageFormIcon.setToolTipText("");

		javax.swing.GroupLayout manageFormIconLayout = new javax.swing.GroupLayout(
				manageFormIcon);
		manageFormIcon.setLayout(manageFormIconLayout);
		manageFormIconLayout.setHorizontalGroup(manageFormIconLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 200, Short.MAX_VALUE));
		manageFormIconLayout.setVerticalGroup(manageFormIconLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		formTitlejLabel.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
		formTitlejLabel.setText("报表查看");

		javax.swing.GroupLayout formjPanelLayout = new javax.swing.GroupLayout(
				formjPanel);
		formjPanel.setLayout(formjPanelLayout);
		formjPanelLayout
				.setHorizontalGroup(formjPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								formjPanelLayout
										.createSequentialGroup()
										.addGap(110, 110, 110)
										.addGroup(
												formjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																formjPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				profitFormIcon,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				201,
																				Short.MAX_VALUE)
																		.addComponent(
																				manageFormIcon,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap(
																				114,
																				Short.MAX_VALUE))
														.addGroup(
																formjPanelLayout
																		.createSequentialGroup()
																		.addGap(35,
																				35,
																				35)
																		.addComponent(
																				viewProfitFormjButton)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				viewManageForm)
																		.addGap(144,
																				144,
																				144))))
						.addGroup(
								formjPanelLayout
										.createSequentialGroup()
										.addGroup(
												formjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																formjPanelLayout
																		.createSequentialGroup()
																		.addGap(387,
																				387,
																				387)
																		.addComponent(
																				formTitlejLabel))
														.addGroup(
																formjPanelLayout
																		.createSequentialGroup()
																		.addGap(287,
																				287,
																				287)
																		.addComponent(
																				formDeadLinejLabel)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				formEYearjComboBox,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				formEYearjLabel)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				formEMonthjComboBox,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				formEMonthjLabel)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				formEDatejComboBox,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				formEDatejLabel)))
										.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(
								formjPanelLayout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												formjPanelLayout
														.createSequentialGroup()
														.addGap(0, 664,
																Short.MAX_VALUE)
														.addComponent(
																jSeparator3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																50,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(56, 56, 56)
														.addComponent(
																jSeparator1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																50,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(5, 5, 5))));
		formjPanelLayout
				.setVerticalGroup(formjPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								formjPanelLayout
										.createSequentialGroup()
										.addGap(19, 19, 19)
										.addComponent(
												formTitlejLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												15,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(27, 27, 27)
										.addGroup(
												formjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																formDeadLinejLabel)
														.addComponent(
																formEYearjComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																formEMonthjComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																formEDatejComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																formEMonthjLabel)
														.addComponent(
																formEYearjLabel)
														.addComponent(
																formEDatejLabel))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												35, Short.MAX_VALUE)
										.addGroup(
												formjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																manageFormIcon,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																profitFormIcon,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(35, 35, 35)
										.addGroup(
												formjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																viewProfitFormjButton)
														.addComponent(
																viewManageForm))
										.addGap(118, 118, 118))
						.addGroup(
								formjPanelLayout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												formjPanelLayout
														.createSequentialGroup()
														.addGap(31, 31, 31)
														.addGroup(
																formjPanelLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jSeparator3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jSeparator1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addContainerGap(460,
																Short.MAX_VALUE))));

		finacialjTabbedPane.addTab("报表查看", formjPanel);

	}

	private void inititalBankAccountJPanel() {
		// TODO Auto-generated method stub
		bankAcocuntjPanel.setPreferredSize(new java.awt.Dimension(830, 460));

		addBankAccountjButton.setText("增加银行账户");
		addBankAccountjButton
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseReleased(java.awt.event.MouseEvent evt) {
						addBankAccountjButtonMouseReleased(evt);
					}
				});

		bankAccountTitlejLabel.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
		bankAccountTitlejLabel.setText("银行账户信息");

		bankAccountNumjLabel.setText("银行账号：");

		findBankAccountNumjTextField.setText("请输入19位银行账户");
		findBankAccountNumjTextField
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						findBankAccountNumjTextFieldMouseClicked(evt);
					}
				});

		findBankAccountNumjButton.setText("查找");
		findBankAccountNumjButton
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseReleased(java.awt.event.MouseEvent evt) {
						findBankAccountNumjButtonMouseReleased(evt);
					}
				});

		bankAccountNamejLabel.setText("账户名称：");

		findBankAccountNamejTextField.setText("请输入银行账户名称");
		findBankAccountNamejTextField
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						bankAccountNamejTextFieldMouseClicked(evt);
					}
				});

		findBankAccountNamejButton.setText("查找");
		findBankAccountNamejButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						findBankAccountNamejButtonActionPerformed(evt);
					}
				});

		initialBankAccountJTable(bankAccountVOPlus, 0);
		javax.swing.GroupLayout bankAcocuntjPanelLayout = new javax.swing.GroupLayout(
				bankAcocuntjPanel);
		bankAcocuntjPanel.setLayout(bankAcocuntjPanelLayout);
		bankAcocuntjPanelLayout
				.setHorizontalGroup(bankAcocuntjPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								bankAcocuntjPanelLayout
										.createSequentialGroup()
										.addContainerGap(170, Short.MAX_VALUE)
										.addGroup(
												bankAcocuntjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																bankAcocuntjPanelLayout
																		.createSequentialGroup()
																		.addGroup(
																				bankAcocuntjPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								bankAcocuntjPanelLayout
																										.createSequentialGroup()
																										.addGroup(
																												bankAcocuntjPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																false)
																														.addGroup(
																																bankAcocuntjPanelLayout
																																		.createSequentialGroup()
																																		.addComponent(
																																				bankAccountNumjLabel)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				findBankAccountNumjTextField,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				354,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																bankAcocuntjPanelLayout
																																		.createSequentialGroup()
																																		.addComponent(
																																				bankAccountNamejLabel)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				findBankAccountNamejTextField,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				354,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)))
																										.addGap(18,
																												18,
																												Short.MAX_VALUE)
																										.addGroup(
																												bankAcocuntjPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																findBankAccountNumjButton)
																														.addComponent(
																																findBankAccountNamejButton)))
																						.addComponent(
																								jScrollPane1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								493,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addContainerGap(
																				162,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																bankAcocuntjPanelLayout
																		.createSequentialGroup()
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				bankAccountTitlejLabel)
																		.addGap(373,
																				373,
																				373))))
						.addGroup(
								bankAcocuntjPanelLayout.createSequentialGroup()
										.addGap(356, 356, 356)
										.addComponent(addBankAccountjButton)
										.addGap(0, 0, Short.MAX_VALUE)));
		bankAcocuntjPanelLayout
				.setVerticalGroup(bankAcocuntjPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								bankAcocuntjPanelLayout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												bankAcocuntjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																bankAccountNumjLabel)
														.addComponent(
																findBankAccountNumjTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																findBankAccountNumjButton))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												16, Short.MAX_VALUE)
										.addGroup(
												bankAcocuntjPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																bankAccountNamejLabel)
														.addComponent(
																findBankAccountNamejTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																findBankAccountNamejButton))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(bankAccountTitlejLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												12, Short.MAX_VALUE)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												339,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(addBankAccountjButton)
										.addGap(16, 16, 16)));

		finacialjTabbedPane.addTab("银行账户管理", bankAcocuntjPanel);

	}

	private void initialBankAccountJTable(ArrayList<BankAccountVOPlus> vos,
			int n) {
		// TODO Auto-generated method stub
		Object[][] bankAccountObjects = null;
		bankAccountObjects = new Object[vos.size()][3];
		int i = 0;
		for (java.util.Iterator<BankAccountVOPlus> t = vos.iterator(); t
				.hasNext(); i++) {
			BankAccountVO vo = t.next();
			bankAccountObjects[i][0] = vo.bankAccountNum;
			bankAccountObjects[i][1] = vo.bankAccountName;
			bankAccountObjects[i][2] = vo.balance;
		}
		if (currentAuthority == Authority.FINANCIALSTAFF_C) {
			bankAccountjTable.setModel(new javax.swing.table.DefaultTableModel(
					bankAccountObjects, new String[] { "银行账号", "账户名称",
							"账户余额（元）" }) {
				Class[] types = new Class[] { java.lang.String.class,
						java.lang.String.class, java.lang.Long.class };
				boolean[] canEdit = new boolean[] { false, false, false };

				public Class getColumnClass(int columnIndex) {
					return types[columnIndex];
				}

				public boolean isCellEditable(int rowIndex, int columnIndex) {
					return canEdit[columnIndex];
				}
			});
		} else if (currentAuthority == Authority.FINANCIALSTAFF_V) {
			bankAccountjTable.setModel(new javax.swing.table.DefaultTableModel(
					bankAccountObjects, new String[] { "银行账号", "账户名称",
							"账户余额（元）" }) {
				Class[] types = new Class[] { java.lang.String.class,
						java.lang.String.class, java.lang.Double.class };
				boolean[] canEdit = new boolean[] { true, true, true };

				public Class getColumnClass(int columnIndex) {
					return types[columnIndex];
				}

				public boolean isCellEditable(int rowIndex, int columnIndex) {
					return canEdit[columnIndex];
				}
			});
		}
		DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();// 设置table内容居中
		tcr.setHorizontalAlignment(SwingConstants.CENTER);// 这句和上句作用一样
		bankAccountjTable.setDefaultRenderer(Object.class, tcr);

		((DefaultTableCellRenderer) bankAccountjTable.getTableHeader()
				.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);// 设置表头居中
		bankAccountjTable.setRowSelectionInterval(n, n);// 设置哪几行被选中
		if (currentAuthority == Authority.FINANCIALSTAFF_V) {
			final JPopupMenu bankAccountjPop = new JPopupMenu();
			final JMenuItem bankAccountSubmitjItem = new JMenuItem("提交");
			final JMenuItem bankAccountDeljItem = new JMenuItem("删除");
			bankAccountSubmitjItem.addMouseListener(/**
			 * @author 1
			 *         监听bankAccount的弹出菜单中的“提交”
			 */
			new MouseListener() {

				@Override
				public void mouseClicked(MouseEvent e) {
					// TODO Auto-generated method stub

				}

				@Override
				public void mousePressed(MouseEvent e) {
					// TODO Auto-generated method stub

				}

				@Override
				public void mouseReleased(MouseEvent e) {
					// TODO Auto-generated method stub
					if (e.getButton() == MouseEvent.BUTTON1) {
						ResultMessage rmsg = null;
						int n = bankAccountjTable.getSelectedRow();
						BankAccountVOPlus voPlus = bankAccountVOPlus.get(n);
						ModifyState state = voPlus.isModify;
						BankAccountVO v = getViewBankAccountVO(n);
						if (state == ModifyState.NEW) {
							try {
								rmsg = bankAccountblController.insert(v);
								setState(
										"提交"
												+ ResultMessage
														.toFriendlyString(rmsg),
										DISPLAY_TIME);
								if (rmsg == ResultMessage.SUCCESS) {
									bankAccountVOPlus.remove(n);
									bankAccountVOPlus.add(n,
											new BankAccountVOPlus(v,
													ModifyState.SYNC));
								}
							} catch (RemoteException e1) {
								// TODO Auto-generated catch block
								e1.printStackTrace();
								setState(REMOTEFAILD, DISPLAY_TIME);
							}
						} else {
							if (v.equals(voPlus.getBankAccountVO())) {
								setState("您未对该行进行修改！", DISPLAY_TIME);
							} else {
								try {
									rmsg = bankAccountblController.update(v);
									setState(ResultMessage
											.toFriendlyString(rmsg),
											DISPLAY_TIME);
									if (rmsg == ResultMessage.SUCCESS) {
										bankAccountVOPlus.remove(n);
										bankAccountVOPlus.add(n,
												new BankAccountVOPlus(v,
														ModifyState.SYNC));
									}
								} catch (RemoteException e1) {
									// TODO Auto-generated catch block
									e1.printStackTrace();
									setState(REMOTEFAILD, DISPLAY_TIME);
								}
							}
						}
					}

				}

				@Override
				public void mouseEntered(MouseEvent e) {
					// TODO Auto-generated method stub

				}

				@Override
				public void mouseExited(MouseEvent e) {
					// TODO Auto-generated method stub

				}

			});
			bankAccountDeljItem.addMouseListener(/**
			 * @author 1
			 *         监听bankAccountjTable上弹出菜单的“删除”
			 */
			new MouseListener() {
				@Override
				public void mouseReleased(MouseEvent e) {
					// TODO Auto-generated method stub
					if (e.getButton() == MouseEvent.BUTTON1) {
						int tempN = 0;
						ResultMessage rmsg = null;
						int n = bankAccountjTable.getSelectedRow();
						BankAccountVOPlus voPlus = bankAccountVOPlus.get(n);
						ModifyState state = voPlus.isModify;
						if (state == ModifyState.NEW) {
							bankAccountVOPlus.remove(n);
							if (n == 0) {
								tempN = 0;
							} else {
								tempN = n - 1;
							}
							initialBankAccountJTable(bankAccountVOPlus, tempN);
						} else {
							Object[] options = { "取消", "删除" };
							int result = JOptionPane.showOptionDialog(null,
									"您确定要删除系统该薪水策略？", "是否删除",
									JOptionPane.DEFAULT_OPTION,
									JOptionPane.QUESTION_MESSAGE, null,
									options, options[0]);
							if (result == JOptionPane.NO_OPTION) {
								try {
									rmsg = bankAccountblController
											.delete(voPlus.getBankAccountVO());
									if (rmsg == ResultMessage.SUCCESS) {
										setState("删除成功:)", DISPLAY_TIME);
										bankAccountVOPlus.remove(n);
										tempN = 0;
										if (n == 0) {
											tempN = 0;
										} else {
											tempN = n - 1;
										}
										initialBankAccountJTable(
												bankAccountVOPlus, tempN);
									} else {
										setState(ResultMessage
												.toFriendlyString(rmsg),
												DISPLAY_TIME);
									}
								} catch (RemoteException e1) {
									// TODO Auto-generated catch block
									e1.printStackTrace();
									setState(REMOTEFAILD, DISPLAY_TIME);
								}
							}
						}
					}
				}

				@Override
				public void mousePressed(MouseEvent e) {
					// TODO Auto-generated method stub

				}

				@Override
				public void mouseExited(MouseEvent e) {
					// TODO Auto-generated method stub

				}

				@Override
				public void mouseEntered(MouseEvent e) {
					// TODO Auto-generated method stub

				}

				@Override
				public void mouseClicked(MouseEvent e) {
					// TODO Auto-generated method stub
				}
			});
			;
			bankAccountjPop.add(bankAccountSubmitjItem);
			bankAccountjPop.add(bankAccountDeljItem);
			MouseInputListener mil = new MouseInputListener() {

				public void mouseClicked(MouseEvent e) {
					processEvent(e);
				}

				public void mousePressed(MouseEvent e) {
					processEvent(e);
				}

				public void mouseReleased(MouseEvent e) {
					processEvent(e);
					if ((e.getModifiers() & MouseEvent.BUTTON3_MASK) != 0
							&& !e.isControlDown() && !e.isShiftDown()) {
						bankAccountjPop.show(bankAccountjTable, e.getX(),
								e.getY());
					}
				}

				public void mouseEntered(MouseEvent e) {
					processEvent(e);
				}

				public void mouseExited(MouseEvent e) {
					processEvent(e);
				}

				public void mouseDragged(MouseEvent e) {
					processEvent(e);
				}

				public void mouseMoved(MouseEvent e) {
					processEvent(e);
				}

				private void processEvent(MouseEvent e) {
					if ((e.getModifiers() & MouseEvent.BUTTON3_MASK) != 0) {
						int modifiers = e.getModifiers();
						modifiers -= MouseEvent.BUTTON3_MASK;
						modifiers |= MouseEvent.BUTTON1_MASK;
						MouseEvent ne = new MouseEvent(e.getComponent(),
								e.getID(), e.getWhen(), modifiers, e.getX(),
								e.getY(), e.getClickCount(), false);
						bankAccountjTable.dispatchEvent(ne);
					}
				}
			};
			bankAccountjTable.addMouseListener(mil);
		}
		bankAccountjTable.putClientProperty("terminateEditOnFocusLost",
				Boolean.TRUE);

		bankAccountjTable.getTableHeader().setReorderingAllowed(false);
		bankAccountjTable.setGridColor(new java.awt.Color(0, 0, 0));
		bankAccountjTable.setName("123"); // NOI18N
		jScrollPane1.setViewportView(bankAccountjTable);
	}

	private void setBankAccountVOs() {
		// TODO Auto-generated method stub
		bankAccountVOPlus = new ArrayList<BankAccountVOPlus>();
		BankAccountVO vo = null;
		BankAccountVOPlus voplus = null;
		ArrayList<BankAccountVO> vos = getbankAccountVOs();
		for (Iterator<BankAccountVO> t = vos.iterator(); t.hasNext();) {
			vo = t.next();
			voplus = new BankAccountVOPlus(vo, ModifyState.SYNC);
			bankAccountVOPlus.add(voplus);
		}
		bankAccountVOPlus.sort(null);
	}

	private ArrayList<BankAccountVO> getbankAccountVOs() {
		// TODO Auto-generated method stub

		// TODO Auto-generated method stub
		ArrayList<BankAccountVO> vos = null;
		try {
			vos = bankAccountblController.show();
			if (vos != null) {
				vos.sort(null);
			}
		} catch (RemoteException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.out.println("远程连接失败");
			setState("远程连接失败", DISPLAY_TIME);
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.out.println("程序错误");
			setState("程序错误", DISPLAY_TIME);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.out.println("读取文件失败");
			setState("读取文件失败", DISPLAY_TIME);
		}
		assert (vos != null) : ("远程获取常量信息失败");
		return vos;
	}

	private void initialVariables() {
		// TODO Auto-generated method stub
		financialjPanel = new javax.swing.JPanel();
		currentAccountNumjLabel = new javax.swing.JLabel();
		accountNamejLabel = new javax.swing.JLabel();
		currentAuthorityjLabel = new javax.swing.JLabel();
		statejLabel = new javax.swing.JLabel();
		stateTitlejLabel = new javax.swing.JLabel();
		finacialjTabbedPane = new javax.swing.JTabbedPane();
		financialManagejPanel = new javax.swing.JPanel();
		financilManageTitlejLabel = new javax.swing.JLabel();
		paymentIconjPanel = new javax.swing.JPanel();
		paymentjButton = new javax.swing.JButton();
		bankAcocuntjPanel = new javax.swing.JPanel();
		addBankAccountjButton = new javax.swing.JButton();
		bankAccountTitlejLabel = new javax.swing.JLabel();
		bankAccountNumjLabel = new javax.swing.JLabel();
		findBankAccountNumjTextField = new javax.swing.JTextField();
		findBankAccountNumjButton = new javax.swing.JButton();
		bankAccountNamejLabel = new javax.swing.JLabel();
		findBankAccountNamejTextField = new javax.swing.JTextField();
		findBankAccountNamejButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		bankAccountjTable = new javax.swing.JTable();
		formjPanel = new javax.swing.JPanel();
		viewProfitFormjButton = new javax.swing.JButton();
		viewManageForm = new javax.swing.JButton();
		formEYearjLabel = new javax.swing.JLabel();
		formEMonthjLabel = new javax.swing.JLabel();
		formEDatejLabel = new javax.swing.JLabel();
		formEYearjComboBox = new javax.swing.JComboBox();
		formEDatejComboBox = new javax.swing.JComboBox();
		formEMonthjComboBox = new javax.swing.JComboBox();
		formDeadLinejLabel = new javax.swing.JLabel();
		jSeparator3 = new javax.swing.JSeparator();
		jSeparator1 = new javax.swing.JSeparator();
		profitFormIcon = new javax.swing.JPanel();
		manageFormIcon = new javax.swing.JPanel();
		formTitlejLabel = new javax.swing.JLabel();
		logjPanel = new javax.swing.JPanel();
		findLogjButton = new javax.swing.JButton();
		logSDatejLabel = new javax.swing.JLabel();
		logSYearjLabel = new javax.swing.JLabel();
		logSMonthjLabel = new javax.swing.JLabel();
		logTypejLabel = new javax.swing.JLabel();
		logTypejComboBox = new JComboBox<LogType>();
		logSYearjComboBox = new javax.swing.JComboBox<Integer>();
		logSDatejComboBox = new javax.swing.JComboBox<Integer>();
		logSMonthjComboBox = new javax.swing.JComboBox<Integer>();
		logEYearjLabel = new javax.swing.JLabel();
		logEMonthjLabel = new javax.swing.JLabel();
		logEDayjLabel = new javax.swing.JLabel();
		logEYearjComboBox = new javax.swing.JComboBox<Integer>();
		logEDatejComboBox = new javax.swing.JComboBox<Integer>();
		logEMonthjComboBox = new javax.swing.JComboBox<Integer>();
		logEDatejLabel = new javax.swing.JLabel();
		jSeparator5 = new javax.swing.JSeparator();
		logTitlejLabel = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		logjTable = new javax.swing.JTable();
		logStartDayjLabel = new javax.swing.JLabel();
		jPanel6 = new javax.swing.JPanel();
		initialFinancejButton = new javax.swing.JButton();
		newFinancejButton = new javax.swing.JButton();
		initialFinaceIconjpanel = new javax.swing.JPanel();
		newFinanceIconjPanel = new javax.swing.JPanel();
		initialFinanceTitlejLabel = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		exitjButton = new javax.swing.JButton();

	}

	private void viewProfitFormjButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		new ProfitForm();
	}// GEN-LAST:event_viewProfitFormjButtonActionPerformed

	private void formEDatejComboBoxActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_formEDatejComboBoxActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_formEDatejComboBoxActionPerformed

	private void formEMonthjComboBoxActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_formEMonthjComboBoxActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_formEMonthjComboBoxActionPerformed

	private void findLogjButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_findLogjButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_findLogjButtonActionPerformed

	private void logTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logTypejComboBoxActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_logTypejComboBoxActionPerformed

	private void logSMonthjComboBoxActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logSMonthjComboBoxActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_logSMonthjComboBoxActionPerformed

	private void logEMonthjComboBoxActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logEMonthjComboBoxActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_logEMonthjComboBoxActionPerformed

	private void initialFinancejButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_initialFinancejButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_initialFinancejButtonActionPerformed

	private void newFinancejButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newFinancejButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_newFinancejButtonActionPerformed

	/**
	 * @param evt
	 */
	private void exitjButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO Auto-generated method stub
		if (evt.getSource() == exitjButton) {
			Object[] options = { "取消", "确定" };
			int result = JOptionPane.showOptionDialog(null, "您确定要退出系统？",
					"是否退出", JOptionPane.DEFAULT_OPTION,
					JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
			if (result == JOptionPane.NO_OPTION) {
				this.dispose();
				new MainFrame();
			}
		}
	}// GEN-LAST:event_exitjButtonActionPerformed

	/**
	 * @param evt
	 */
	private void findBankAccountNamejButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_findBankAccountNamejButtonMouseReleased
		// TODO add your handling code here:
		if (evt.getSource() == findBankAccountNamejButton) {
			String findBankAccountName = findBankAccountNamejTextField
					.getText();
			ResultMessage rmsg = InputCheck.checkInputName(findBankAccountName);
			if (rmsg == ResultMessage.VALID) {
				int i = 0;
				BankAccountVO tempVO = null;
				for (Iterator<BankAccountVOPlus> t = bankAccountVOPlus
						.iterator(); t.hasNext(); i++) {
					tempVO = t.next();
					if (tempVO.bankAccountName.equals(findBankAccountName)) {
						break;
					}
				}
				if (i < bankAccountVOPlus.size()) {
					bankAccountjTable.setRowSelectionInterval(i, i);// 设置哪几行被选中
					setState("该银行账户在第" + (i + 1) + "行", 5);
				} else {
					setState("系统中无该银行账户", 5);
				}
			} else {
				String msg = ResultMessage.toFriendlyString(rmsg);
				setState("机构" + msg, 5);
			}
		}

	}// GEN-LAST:event_findBankAccountNamejButtonActionPerformed

	private void paymentIconjPanelMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_paymentIconjPanelMouseReleased
		// TODO add your handling code here:
	}// GEN-LAST:event_paymentIconjPanelMouseReleased

	/**
	 * @param evt
	 */
	private void addBankAccountjButtonMouseReleased(
			java.awt.event.MouseEvent evt) {// GEN-FIRST:event_addBankAccountjButton2ActionPerformed
		// TODO add your handling code here:
		if (evt.getSource() == addBankAccountjButton) {
			bankAccountVOPlus.add(new BankAccountVOPlus("", "", 0,
					ModifyState.NEW));
			initialBankAccountJTable(bankAccountVOPlus,
					bankAccountVOPlus.size() - 1);
		}
	}// GEN-LAST:event_addBankAccountjButtonMouseReleased

	/**
	 * @param evt
	 */
	private void findBankAccountNumjTextFieldMouseClicked(
			java.awt.event.MouseEvent evt) {// GEN-FIRST:event_bankAccountNumjTextFieldMouseClicked
		// TODO add your handling code here:
		findBankAccountNumjTextField.setText("");
	}// GEN-LAST:event_bankAccountNumjTextFieldMouseClicked

	/**
	 * @param evt
	 */
	private void bankAccountNamejTextFieldMouseClicked(
			java.awt.event.MouseEvent evt) {// GEN-FIRST:event_bankAccountNamejTextFieldMouseClicked
		// TODO add your handling code here:
		findBankAccountNamejTextField.setText("");
	}// GEN-LAST:event_bankAccountNamejTextFieldMouseClicked

	/**
	 * @param evt
	 */
	private void findBankAccountNumjButtonMouseReleased(
			java.awt.event.MouseEvent evt) {// GEN-FIRST:event_findBankAccountNumjButtonMouseReleased
		// TODO add your handling code here:
		if (evt.getSource() == findBankAccountNumjButton) {
			String findBankAccountNum = findBankAccountNumjTextField.getText();
			ResultMessage rmsg = InputCheck.checkInputNum(findBankAccountNum,
					19);
			if (rmsg == ResultMessage.VALID) {
				int i = 0;
				BankAccountVO tempVO = null;
				for (Iterator<BankAccountVOPlus> t = bankAccountVOPlus
						.iterator(); t.hasNext(); i++) {
					tempVO = t.next();
					if (tempVO.bankAccountNum.equals(findBankAccountNum)) {
						break;
					}
				}
				if (i < bankAccountVOPlus.size()) {
					bankAccountjTable.setRowSelectionInterval(i, i);// 设置哪几行被选中
					setState("该账户在第" + (i + 1) + "行", 5);
				} else {
					setState("系统中无该银行账户", 5);
				}
			} else {
				String msg = ResultMessage.toFriendlyString(rmsg);
				setState("银行" + msg, 5);
			}
		}
	}

	private void paymentjButtonActionPerformed(java.awt.event.ActionEvent evt) {
		new PayRep();
	}

	private void viewManageFormMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_viewManageFormMouseReleased
		new BusinessForm();
	}// GEN-LAST:event_viewManageFormMouseReleased

	private void findLogjButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_findLogjButtonMouseReleased
		if (evt.getSource() == findLogjButton) {
			String startT = logSYearjComboBox.getSelectedItem() + "-"
					+ logSMonthjComboBox.getSelectedItem() + "-"
					+ logSDatejComboBox.getSelectedItem();
			String endT = logEYearjComboBox.getSelectedItem() + "-"
					+ logEMonthjComboBox.getSelectedItem() + "-"
					+ logEDatejComboBox.getSelectedItem();
			if (startT.compareTo(endT) <= 0) {
				LogType type = (LogType) logTypejComboBox.getSelectedItem();
				if (logVOs != null) {
					if (logVOs.size() == 0) {
						ComponentFactory.setState("该时间段无日志",
								ComponentFactory.DISPLAY_TIME, statejLabel);
					} else {
						setLogVOs(startT, endT, type);
						initialLogJTable(logVOs);
					}
				} else {
					ComponentFactory.setState("系统程序错误",
							ComponentFactory.DISPLAY_TIME, statejLabel);
				}
			} else {
				ComponentFactory.setState("截止日期早于开始日期",
						ComponentFactory.DISPLAY_TIME, statejLabel);
			}
		}
	}

	private void newFinanceIconjPanelMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_newFinanceIconjPanelMouseReleased
	}// GEN-LAST:event_newFinanceIconjPanelMouseReleased

	private void logEYearjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logEYearjComboBoxActionPerformed
	}// GEN-LAST:event_logEYearjComboBoxActionPerformed

	/**
	 * @param argss
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					FinancialStaffJFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					FinancialStaffJFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					FinancialStaffJFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					FinancialStaffJFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				FinancialStaffJFrame financialStaffJFrame = new FinancialStaffJFrame();
				
			}
		});
	}

	private BankAccountVO getViewBankAccountVO(int n) {
		// TODO Auto-generated method stub
		String bankAccountNum = null;
		String bankAccountName = null;
		double balance = -1;
		try {
			bankAccountNum = (String) bankAccountjTable.getValueAt(n, 0);
			bankAccountName = (String) bankAccountjTable.getValueAt(n, 1);
			balance = (Double) bankAccountjTable.getValueAt(n, 2);
			assert (bankAccountName != null && bankAccountNum != null && balance != -1) : ("您输入的银行信息不完整！");
		} catch (ClassCastException e) {
			e.printStackTrace();
			setState("您输入的值类型不正确：(", DISPLAY_TIME);
		} catch (AssertionError e) {
			setState("您输入的银行账户信息不完整！", DISPLAY_TIME);
			System.out.println(e.getMessage());
		}
		return new BankAccountVO(bankAccountNum, bankAccountName, balance);
	}

	/**
	 * 改变statejlabel的提示信息，并在五秒后改回"空闲"
	 * 
	 * @param str
	 */
	public void setState(String str, long time) {
		statejLabel.setText(str);
		final Runnable setSateTextFieldText = new Runnable() {
			public void run() {
				statejLabel.setText("空闲");
			}
		};
		final ScheduledFuture<?> beeperHandle = scheduler.scheduleAtFixedRate(
				setSateTextFieldText, time, time, TimeUnit.SECONDS);
		scheduler.schedule(new Runnable() {
			public void run() {
				beeperHandle.cancel(true);
			}
		}, time, TimeUnit.SECONDS);
	}

	private void setLogVOs(String startTime, String endTime, LogType type) {
		logVOs = getLogVOs(startTime, endTime, type);
		if (logVOs != null) {
			System.out.println("得到的log数据：" + logVOs.size());
		} else {
			System.out.println("得到的log数据为空!");
		}
		logVOs.sort(null);
	}

	/**
	 * 获得
	 * 
	 * @return
	 */
	private ArrayList<LogVO> getLogVOs(String startTime, String endTime,
			LogType type) {
		ArrayList<LogVO> vos = null;
		vos = logblController.show(startTime, endTime, type);
		assert (vos != null) : ("远程获取账户信息失败");
		vos.sort(null);
		assert (vos != null) : ("获取日志失败");
		return vos;
	}

	// bl相关变量
	private LogBLService ctr_log;
	private Authority currentAuthority = null;
	private String currentOptorId = null;
	private ArrayList<BankAccountVO> bankAccountVOs = null;
	private ArrayList<BankAccountVOPlus> bankAccountVOPlus = null;
	private ArrayList<LogVO> logVOs = null;
	private ControllerFactoryblService controllerFactoryblService = ControllerFactoryImpl
			.getInstance();
	private BankAccountBLService bankAccountblController = controllerFactoryblService
			.getBankAccountController();
	private LogBLService logblController = controllerFactoryblService
			.getLogController();
	private final ScheduledExecutorService scheduler = Executors
			.newScheduledThreadPool(1);
	private JComboBox<Authority> authorityjComboBox = ComponentFactory
			.getAuthorityJComboBox();
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel accountNamejLabel;
	private javax.swing.JButton addBankAccountjButton;
	private javax.swing.JLabel bankAccountNamejLabel;
	private javax.swing.JTextField findBankAccountNamejTextField;
	private javax.swing.JLabel bankAccountNumjLabel;
	private javax.swing.JTextField findBankAccountNumjTextField;
	private javax.swing.JLabel bankAccountTitlejLabel;
	private javax.swing.JPanel bankAcocuntjPanel;
	private javax.swing.JTable bankAccountjTable;
	private javax.swing.JLabel currentAccountNumjLabel;
	private javax.swing.JLabel currentAuthorityjLabel;
	private javax.swing.JButton exitjButton;
	private javax.swing.JTabbedPane finacialjTabbedPane;
	private javax.swing.JPanel financialManagejPanel;
	private javax.swing.JPanel financialjPanel;
	private javax.swing.JLabel financilManageTitlejLabel;
	private javax.swing.JButton findBankAccountNamejButton;
	private javax.swing.JButton findBankAccountNumjButton;
	private javax.swing.JButton findLogjButton;
	private javax.swing.JLabel formDeadLinejLabel;
	private javax.swing.JComboBox formEDatejComboBox;
	private javax.swing.JLabel formEDatejLabel;
	private javax.swing.JComboBox formEMonthjComboBox;
	private javax.swing.JLabel formEMonthjLabel;
	private javax.swing.JComboBox formEYearjComboBox;
	private javax.swing.JLabel formEYearjLabel;
	private javax.swing.JLabel formTitlejLabel;
	private javax.swing.JPanel formjPanel;
	private javax.swing.JPanel initialFinaceIconjpanel;
	private javax.swing.JLabel initialFinanceTitlejLabel;
	private javax.swing.JButton initialFinancejButton;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator5;
	private javax.swing.JComboBox<Integer> logEDatejComboBox;
	private javax.swing.JLabel logEDatejLabel;
	private javax.swing.JLabel logEDayjLabel;
	private javax.swing.JComboBox<Integer> logEMonthjComboBox;
	private javax.swing.JLabel logEMonthjLabel;
	private javax.swing.JComboBox<Integer> logEYearjComboBox;
	private javax.swing.JLabel logEYearjLabel;
	private javax.swing.JComboBox<Integer> logSDatejComboBox;
	private javax.swing.JLabel logSDatejLabel;
	private javax.swing.JComboBox<Integer> logSMonthjComboBox;
	private javax.swing.JLabel logSMonthjLabel;
	private javax.swing.JComboBox<Integer> logSYearjComboBox;
	private javax.swing.JLabel logSYearjLabel;
	private javax.swing.JLabel logStartDayjLabel;
	private javax.swing.JLabel logTitlejLabel;
	private javax.swing.JComboBox<LogType> logTypejComboBox;
	private javax.swing.JLabel logTypejLabel;
	private javax.swing.JPanel logjPanel;
	private javax.swing.JTable logjTable;
	private javax.swing.JPanel manageFormIcon;
	private javax.swing.JPanel newFinanceIconjPanel;
	private javax.swing.JButton newFinancejButton;
	private javax.swing.JPanel paymentIconjPanel;
	private javax.swing.JButton paymentjButton;
	private javax.swing.JPanel profitFormIcon;
	private javax.swing.JLabel stateTitlejLabel;
	private javax.swing.JLabel statejLabel;
	private javax.swing.JButton viewManageForm;
	private javax.swing.JButton viewProfitFormjButton;
	// End of variables declaration//GEN-END:variables
	/**
	 * 远程连接失败！
	 */
	private final static String REMOTEFAILD = "远程连接失败！";
	/**
	 * 5秒的展示时间，之后又展示空闲
	 */
	private final static long DISPLAY_TIME = 5;
}
