/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.warehousemanui;

import java.awt.*;

import .*;

import ui.mainFrame.MainFrame;
import ui.receiptui.InStockRep;
import ui.receiptui.OutStockRep;

/**
 *
 * @author G
 */
public class WarehousePanel extends .JFrame {
	
	

    /**
     * Creates new form NewJFrame
     */
    public WarehousePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	/**
    	 * 设置窗体大小为不可变
    	 */
    	this.setResizable(false);
    	/**
    	 * 设置窗体在中部出现
    	 */
    	Toolkit tk = Toolkit.getDefaultToolkit();
    	Dimension screensize = tk.getScreenSize();
    	int screenh = screensize.height;
    	int screenw = screensize.width;
    	this.setSize(800, 500);
    	this.setLocation(screenw/2-this.getWidth()/2, screenh/2-this.getHeight()/2);
    	

        jProgressBar2 = new .JProgressBar();
        jLabel1 = new .JLabel();
        jLabel2 = new .JLabel();
        jProgressBar1 = new .JProgressBar();
        jLabel3 = new .JLabel();
        jProgressBar3 = new .JProgressBar();
        jLabel4 = new .JLabel();
        jProgressBar4 = new .JProgressBar();
        jLabel5 = new .JLabel();
        jProgressBar5 = new .JProgressBar();
        jLabel6 = new .JLabel();
        jProgressBar6 = new .JProgressBar();
        jLabel7 = new .JLabel();
        jProgressBar7 = new .JProgressBar();
        jLabel8 = new .JLabel();
        jProgressBar8 = new .JProgressBar();
        jButton1 = new .JButton();
        jButton2 = new .JButton();
        exit = new .JButton();
        jLabel9 = new .JLabel();
        jButton4 = new .JButton();
        jButton5 = new .JButton();
        jButton6 = new .JButton();
        jButton7 = new JButton();
        back = new JButton();
  

        setDefaultCloseOperation(.WindowConstants.EXIT_ON_CLOSE);

        jProgressBar2.setToolTipText("");
        jProgressBar2.setValue(20);

        jLabel1.setText("北京01");

        jLabel2.setText("北京02");

        jProgressBar1.setValue(30);

        jLabel3.setText("上海03");

        jProgressBar3.setValue(35);

        jLabel4.setText("上海04");

        jProgressBar4.setToolTipText("");
        jProgressBar4.setValue(50);

        jLabel5.setText("南京05");

        jProgressBar5.setValue(60);

        jLabel6.setText("南京06");

        jProgressBar6.setValue(40);

        jLabel7.setText("广州07");

        jProgressBar7.setValue(15);

        jLabel8.setText("广州08");

        jProgressBar8.setValue(20);

        jButton1.setText("出库单填写");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("入库单填写");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        exit.setText("退出");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("当前账户：大玉儿");

        jButton4.setText("调整分区");
        
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("输入最初库存数量");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("盘点仓库所有货物");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("库存查看");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        .GroupLayout layout = new .GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
            .addGroup(.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addComponent(exit))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jProgressBar2, .GroupLayout.PREFERRED_SIZE, 76, .GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jProgressBar5, .GroupLayout.PREFERRED_SIZE, 76, .GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar1, .GroupLayout.PREFERRED_SIZE, 78, .GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar6, .GroupLayout.PREFERRED_SIZE, 78, .GroupLayout.PREFERRED_SIZE)))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar3, .GroupLayout.PREFERRED_SIZE, 78, .GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar7, .GroupLayout.PREFERRED_SIZE, 78, .GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar4, .GroupLayout.PREFERRED_SIZE, 84, .GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar8, .GroupLayout.PREFERRED_SIZE, 84, .GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, .GroupLayout.PREFERRED_SIZE, 166, .GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, .GroupLayout.PREFERRED_SIZE, 167, .GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, .GroupLayout.PREFERRED_SIZE, 162, .GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, .GroupLayout.PREFERRED_SIZE, 167, .GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton6, .GroupLayout.PREFERRED_SIZE, 167, .GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(jLabel9))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, .GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar5, .GroupLayout.Alignment.TRAILING, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                    .addGroup(.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jProgressBar2, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jProgressBar1, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jProgressBar3, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)))
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressBar7, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addComponent(jProgressBar6, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))))
                    .addGroup(.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressBar4, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar8, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                            .addGroup(.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8, .GroupLayout.PREFERRED_SIZE, 16, .GroupLayout.PREFERRED_SIZE)))))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, .GroupLayout.PREFERRED_SIZE, 55, .GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, .GroupLayout.PREFERRED_SIZE, 55, .GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, .GroupLayout.PREFERRED_SIZE, 55, .GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, .GroupLayout.PREFERRED_SIZE, 53, .GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, .GroupLayout.PREFERRED_SIZE, 49, .GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, .GroupLayout.PREFERRED_SIZE, 55, .GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	OutStockRep out = new OutStockRep();
    	out.setVisible(true);
    	this.dispose();
    	
    	
    	
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed    	
    	InStockRep in = new InStockRep();
    	in.setVisible(true);
    	this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    	//TODO退出
    	MainFrame mf = new MainFrame();
    	mf.setVisible(true);
    	this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    	DivisionChangePanel dc = new DivisionChangePanel();
    	dc.setVisible(true);
    	this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    	
    	InitialStockNumPanel ini = new InitialStockNumPanel();
    	ini.setVisible(true);
    	this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    	
    	StockShowPanel ss = new StockShowPanel();
    	ss.setVisible(true);
    	this.dispose();
    	
    	
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    	StockCheckPanel sc = new StockCheckPanel();
    	sc.setVisible(true);
    	this.dispose();
    	
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (.UIManager.LookAndFeelInfo info : .UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    .UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarehousePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarehousePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarehousePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarehousePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarehousePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private .JButton jButton1;
    private .JButton jButton2;
    private .JButton exit;
    private .JButton jButton4;
    private .JButton jButton5;
    private .JButton jButton6;
    private .JButton jButton7;
    private JButton back;//返回
    private .JLabel jLabel1;
    private .JLabel jLabel2;
    private .JLabel jLabel3;
    private .JLabel jLabel4;
    private .JLabel jLabel5;
    private .JLabel jLabel6;
    private .JLabel jLabel7;
    private .JLabel jLabel8;
    private .JLabel jLabel9;
    private .JProgressBar jProgressBar1;
    private .JProgressBar jProgressBar2;
    private JProgressBar jProgressBar3;
    private JProgressBar jProgressBar4;
    private JProgressBar jProgressBar5;
    private JProgressBar jProgressBar6;
    private JProgressBar jProgressBar7;
    private JProgressBar jProgressBar8;
 

    // End of variables declaration//GEN-END:variables
}
