package ui.warehousemanui;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import .*;

import bl.controllerfactorybl.ControllerFactoryImpl;
import bl.stockbl.StockController;
import blservice.stockblservice.StockBLService;
import ui.mainFrame.MainFrame;
/**
 *
 * @author G
 */
public class StockCheckPanel extends .JFrame {

    /**
     * Creates new form StockCheck
     */
    public StockCheckPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	/**
    	 * 点叉关闭窗口
    	 */
    	this.setDefaultCloseOperation(EXIT_ON_CLOSE);

    	/**
    	 * 设置窗体大小
    	 */
    	this.setSize(600, 430);
    	/**
    	 * 设置窗体大小为不可变
    	 */
    	this.setResizable(false);
    	/**
    	 * 设置窗体在中部出现
    	 */
    	Toolkit tk = Toolkit.getDefaultToolkit();
    	Dimension screensize = tk.getScreenSize();
    	int screenh = screensize.height;
    	int screenw = screensize.width;
    	this.setLocation(screenw/2-this.getWidth()/2, screenh/2-this.getHeight()/2);

    	
        confirm = new .JButton();
        exit = new .JButton();
        usernamelabel = new .JLabel();
        jLabel1 = new .JLabel();
        jComboBox1 = new .JComboBox();
        jLabel3 = new .JLabel();
        jComboBox2 = new .JComboBox();
        jLabel7 = new .JLabel();
        jLabel9 = new .JLabel();
        jLabel11 = new .JLabel();
        jComboBox3 = new .JComboBox();
        jLabel14 = new .JLabel();
        jComboBox7 = new .JComboBox();
        jLabel15 = new .JLabel();
        innum = new .JLabel();
        jLabel17 = new .JLabel();
        outnum = new .JLabel();
 
        back = new .JButton();

        confirm.setText("确认");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        exit.setText("退出");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        back.setText("返回");
        back.addActionListener(new ActionListener(){
        	public void actionPerformed(ActionEvent evt) {
        		backActionPerformed(evt);
        	}
        });
        
     
        usernamelabel.setText("当前账户："+username);
        
       


        jLabel1.setText("月");

        jComboBox1.setModel(new .DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel3.setText("日");

        jComboBox2.setModel(new DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel7.setText("起始日期：");

        jLabel9.setText("结束日期：");

        jLabel11.setText("月");

        jComboBox3.setModel(new DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel14.setText("日");

        jComboBox7.setModel(new DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel15.setText("出库数量：");

        innum.setText("5000");

        jLabel17.setText("入库数量：");

        outnum.setText("2000");

    

        back.setText("返回");

        .GroupLayout layout = new .GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
            .addGroup(.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, .GroupLayout.PREFERRED_SIZE, 76, .GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, .GroupLayout.PREFERRED_SIZE, 76, .GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox7, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, .GroupLayout.PREFERRED_SIZE, 83, .GroupLayout.PREFERRED_SIZE)
                        
                            .addComponent(jLabel15, .GroupLayout.PREFERRED_SIZE, 83, .GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING)
                  
                            .addComponent(outnum)
                            .addComponent(innum))))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usernamelabel)
                        .addGap(26, 26, 26)
                        .addComponent(exit, .GroupLayout.PREFERRED_SIZE, 59, .GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(back, .GroupLayout.Alignment.LEADING, .GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(confirm, .GroupLayout.PREFERRED_SIZE, 59, .GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.LEADING)
                    .addComponent(exit)
                    .addComponent(usernamelabel))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox3, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox7, .GroupLayout.PREFERRED_SIZE, .GroupLayout.DEFAULT_SIZE, .GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, .GroupLayout.PREFERRED_SIZE, 54, .GroupLayout.PREFERRED_SIZE)
                    .addComponent(innum))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, .GroupLayout.PREFERRED_SIZE, 54, .GroupLayout.PREFERRED_SIZE)
                    .addComponent(outnum)
                    .addComponent(back))
                .addGap(22, 22, 22)
                )
        );
    }// </editor-fold>                        

    
	StockBLService s = ControllerFactoryImpl.getInstance().getStockController();
 
    private void confirmActionPerformed(ActionEvent evt) {                                         
        String startMonth = (String) jComboBox1.getSelectedItem();
        String startDay = (String) jComboBox2.getSelectedItem();
        String endMonth = (String) jComboBox3.getSelectedItem();
        String endDay = (String) jComboBox7.getSelectedItem();
        
        String result = s.checkStock(startMonth, startDay, endMonth, endDay);
        
        showResult(result);
        
    }                                        

    /**
     * 从结果字符串中提取出入库出库数量并显示
     * @param result
     */
    private static void showResult(String result) {
    	StockCheckPanel s = new StockCheckPanel();
    	Pattern p = Pattern.compile("\\d+(\\.\\d+)?");
    	Matcher m = p.matcher(result);
    	m.find();
    	s.innum.setText(m.group());
    	m.find();
    	s.outnum.setText(m.group());
    	 	
    }
    
    
    private void exitActionPerformed(ActionEvent evt) {
    	MainFrame mf = new MainFrame();
    	mf.setVisible(true);
    	this.dispose();
    }

    private void backActionPerformed(ActionEvent evt) {
    	WarehousePanel w = new WarehousePanel();
		w.setVisible(true);
		this.dispose();
		
    }
    
    public void setUsername(String username) {
		this.username = username;
	}
    
    // Variables declaration - do not modify                     
    private .JButton back;
    private .JButton confirm;
    private .JButton exit;
    private .JComboBox jComboBox1;
    private .JComboBox jComboBox2;
    private .JComboBox jComboBox3;
    private .JComboBox jComboBox7;
    private .JLabel jLabel1;
    private .JLabel usernamelabel;
    private .JLabel jLabel11;
    private .JLabel jLabel14;
    private .JLabel jLabel15;
    private .JLabel innum;
    private .JLabel jLabel17;
    private .JLabel outnum;
  
    private .JLabel jLabel3;
    private .JLabel jLabel7;
    private .JLabel jLabel9;
    private String username = "大玉儿";
    // End of variables declaration                   
}



