/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.warehousemanui;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;

import javax.swing.*;

import main.MainFrame;
import VO.StockVO;
import bl.controllerfactorybl.ControllerFactoryImpl;
import bl.loginbl.Loginbl;
import bl.loginbl.LoginblController;
import blservice.stockblservice.StockBLService;
import ui.Img;
import ui.receiptui.generalUI.InStockRep;
import ui.receiptui.generalUI.OutStockRep;

/**
 *
 * @author G
 */
public class WarehousePanel extends javax.swing.JFrame {
	
	

    /**
     * Creates new form NewJFrame
     */
    public WarehousePanel() {
    	try {
			username = new LoginblController().getCurrentName();
		} catch (RemoteException e) {
			e.printStackTrace();
		}
    	
    	panel=new JPanel(){
			/* (non-Javadoc)
			 * @see javax.swing.JComponent#paintComponent(java.awt.Graphics)
			 */
			@Override
			protected void paintComponent(Graphics g) {
				g.drawImage(Img.getBackground_main(),0, 0, null);
			}
		};
    	
	
        initComponents();
        this.setContentPane(panel);
        
      
		addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent e) {
				mousePressedX = e.getX();
				mousePressedY = e.getY();
			}
		});
		addMouseMotionListener(new MouseMotionAdapter() {
			public void mouseDragged(MouseEvent e) {
				int x = (int) getLocation().getX();
				int y = (int) getLocation().getY();
				setLocation(x + e.getX() - mousePressedX, y + e.getY()
						- mousePressedY);
			}
		});
		
		this.setUndecorated(true);
		this.setBackground(new Color(0,0,0,0));        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	/**
    	 * 设置窗体大小为不可变
    	 */
    	this.setResizable(false);
    	/**
    	 * 设置窗体在中部出现
    	 */
    	Toolkit tk = Toolkit.getDefaultToolkit();
    	Dimension screensize = tk.getScreenSize();
    	int screenh = screensize.height;
    	int screenw = screensize.width;
    	this.setSize(800, 500);
    	this.setLocation(screenw/2-this.getWidth()/2, screenh/2-this.getHeight()/2);
    	/**
    	 * 关闭窗口
    	 */
    	setDefaultCloseOperation(EXIT_ON_CLOSE);
    	
    	this.setVisible(true);


        Peking1 = new javax.swing.JProgressBar();      
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Peking2 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        Shanghai1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        Shanghai2 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        Nanjing1 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        Nanjing2 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        Guangzhou1 = new JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        Guangzhou2 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new JButton();
        back = new JButton();
  
        panel.add(Guangzhou1);
//        Guangzhou1.setBounds(x, y, width, height);
        panel.add(Guangzhou2);
        panel.add(Nanjing1);
        panel.add(Nanjing2);
        panel.add(Peking1);
        Peking1.setBounds(20, 10, 50, 50);
        panel.add(Peking2);
        panel.add(Shanghai1);
        panel.add(Shanghai2);
        panel.add(back);
        panel.add(exit);
        panel.add(jButton1);
        panel.add(jButton2);
        panel.add(jButton4);
        panel.add(jButton5);
        panel.add(jButton6);
        panel.add(jButton7);
        panel.add(jLabel1);
        panel.add(jLabel2);
        panel.add(jLabel3);
        panel.add(jLabel4);
        panel.add(jLabel5);
        panel.add(jLabel6);
        panel.add(jLabel7);
        panel.add(jLabel8);
        panel.add(jLabel9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //TODO to show, 1000--->10  
        showProgressBar(Peking1, 10, Color.PINK);
        showProgressBar(Peking2, 10, Color.PINK);
        showProgressBar(Shanghai1, 10, Color.BLUE);
        showProgressBar(Shanghai2, 10, Color.BLUE);
        showProgressBar(Nanjing1, 10, Color.BLUE);
        showProgressBar(Nanjing2, 10, Color.BLUE);
        showProgressBar(Guangzhou1, 10, Color.BLUE);
        showProgressBar(Guangzhou2, 10, Color.BLUE);

        jLabel1.setText("北京01");

        jLabel2.setText("北京02");

        

        jLabel3.setText("上海03");


        jLabel4.setText("上海04");

        
      

        jLabel5.setText("南京05");

        
        jLabel6.setText("南京06");

      

        jLabel7.setText("广州07");

       

        jLabel8.setText("广州08");

        //TODO  显示进度条
        showProcess();
        
        jButton1.setText("出库单填写");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("入库单填写");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        exit.setText("退出");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("当前账户："+username);

        jButton4.setText("调整分区");
        
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("输入最初库存数量");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("盘点仓库所有货物");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButton6ActionPerformed(evt);
				} catch (ClassNotFoundException e) {
					e.printStackTrace();
				} catch (NotBoundException e) {
					e.printStackTrace();
				} catch (IOException e) {
					e.printStackTrace();
				}
            }
        });

        jButton7.setText("库存查看");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

    }
    

    
  

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	JFrame frame = new JFrame();
    	
    	frame.setResizable(false);
    	Toolkit tk = Toolkit.getDefaultToolkit();
    	Dimension screensize = tk.getScreenSize();
    	int screenh = screensize.height;
    	int screenw = screensize.width;
    	frame.setSize(500, 600);
    	frame.setLocation(screenw/2-this.getWidth()/2, screenh/2-this.getHeight()/2);	
    	frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
    	
		OutStockRep out = new OutStockRep(frame);
    	frame.setContentPane(out);
    	frame.setVisible(true);
    	this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed    	
    	JFrame frame = new JFrame();
    	
    	frame.setResizable(false);
    	Toolkit tk = Toolkit.getDefaultToolkit();
    	Dimension screensize = tk.getScreenSize();
    	int screenh = screensize.height;
    	int screenw = screensize.width;
    	frame.setSize(500, 600);
    	frame.setLocation(screenw/2-this.getWidth()/2, screenh/2-this.getHeight()/2);	
    	frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
    	
		InStockRep in = new InStockRep(frame);
    	frame.setContentPane(in);
    	frame.setVisible(true);
    	
    	this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    	this.dispose();
    	new MainFrame();
    	
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    	DivisionChangePanel dc = new DivisionChangePanel();
    	dc.setVisible(true);
    	this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    	
    	InitialStockNumPanel ini = new InitialStockNumPanel();
    	ini.setVisible(true);
    	this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    StockBLService s = ControllerFactoryImpl.getInstance().getStockController();
    
    /**
  	 * 
  	 */
    //TODO 

  	public void showProcess() {
  		try {

			Peking1.setValue(s.checkPresentStockQuantity(1));
			System.out.println("block1 "+s.checkPresentStockQuantity(1));
			Peking2.setValue(s.checkPresentStockQuantity(2));
			System.out.println("block2 "+s.checkPresentStockQuantity(2));
			Nanjing1.setValue(s.checkPresentStockQuantity(3));
			System.out.println("block3 "+s.checkPresentStockQuantity(3));
			Nanjing2.setValue(s.checkPresentStockQuantity(4));
			System.out.println("block4 "+s.checkPresentStockQuantity(4));
			Shanghai1.setValue(s.checkPresentStockQuantity(5));
			System.out.println("block5 "+s.checkPresentStockQuantity(5));
			Shanghai2.setValue(s.checkPresentStockQuantity(6));
			System.out.println("block6 "+s.checkPresentStockQuantity(6));
			Guangzhou1.setValue(s.checkPresentStockQuantity(7));
			System.out.println("block7 "+s.checkPresentStockQuantity(7));
			Guangzhou2.setValue(s.checkPresentStockQuantity(8));
			System.out.println("block8 "+s.checkPresentStockQuantity(8));
		
		} catch (ClassNotFoundException | NotBoundException | IOException e) {
			//
			System.out.println("进度条显示崩了");
			
		}
  		
  	}
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException, NotBoundException, IOException {//GEN-FIRST:event_jButton6ActionPerformed
    	
    	StockShowPanel ss = new StockShowPanel();
    	ss.setVisible(true);
    	this.dispose();
    	
    	
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    	StockCheckPanel sc = new StockCheckPanel();
    	sc.setVisible(true);
    	this.dispose();
    	
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new WarehousePanel();
        
    }
    
    private void showProgressBar(JProgressBar bar, int max, Color color) {
    	bar.setMaximum(max);
    	bar.setForeground(color);
    	bar.setBackground(color);
    	bar.setOpaque(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private JButton back;//返回
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar Peking2;
    private JProgressBar Peking1;
    private JProgressBar Shanghai1;
    private JProgressBar Shanghai2;
    private JProgressBar Nanjing1;
    private JProgressBar Nanjing2;
    private JProgressBar Guangzhou1;
    private JProgressBar Guangzhou2;
    private String username;
    private int mousePressedX;
	private int mousePressedY;
	private JPanel panel;

    // End of variables declaration//GEN-END:variables
}
