package util.enumData;

public enum GoodsLogisticState {
	SENDED, SENDER_BUSINESSOFFICE_ARRIVED, 
	SENDER_TRANSCENTER_ARRIVED, RECEIVER_TRANSCENTER_ARRIVED, 
	RECEIVER_BUSINESSOFFICE_ARRIVED, DELIVERING, SIGNED, 
	BROKEN_OR_LOST
}
