package util.enumData;

public enum LogType {
	/**
	 * 与用例一一对应
	 */
	BUSINESS_OFFICER_CAR_MANAGEMENT,
	GET_AND_DELIVER,
	ADD_A_CASHREP,
	/**
	 * 司机管理
	 */
	DRIVER_MANAGEMENT,
	/**
	 * 车辆管理
	 */
	CAR_MANAGEMENT,
	INSTOCK_MANAGEMENT,
	STOCK_MANAGEMENT,
	OUTSTOCK_MANAGEMENT,
	AUTHORITY_MANAGEMENT,
	USER_ACCOUNT_MANAGEMENT,
	ADD_A_GOODS,
	END_A_GOODS,
	TRANSFER_CTR_SHIP_MANAGEMENT,
	TRANSFER_CTR_RECEPTION,
	MONEY_IN_AND_OUT_MANAGEMENT,
	BANKACCOUNT_MANAGEMENT,
	CHECK_LOG,
	CHECK_FORM,
	CHECK_BANKACOUNT,
	PERSONNEL_MANAGEMENT,
	DOCUMENT_CHECK,
	/**
	 * 常量制定
	 */
	DECISION_CONST,
	/**
	 * 薪水策略
	 */
	DECISION_SALARYPOLICY,
	/**
	 * 机构管理
	 */
	INSTITUTION_MANAGEMENT,
	
}
